spring:
  application:
    name: Algamoney-API
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    deserialization:
      fail-on-unknown-properties: true
    date-format: yyyy-MM-dd
  jpa:
    database: MYSQL
    show-sql: true
  datasource:
    url: jdbc:mysql://mysql_algamoneyapi:3306/algamoneyapi?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: basic-security
algamoney:
  permitted-origin: http://localhost:8000